// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyAwlVjnGWo1C2i4vXuh2nz5uAZCUTgJY44',
      appId: '1:370553554615:web:f495f679d5166afa08ef32',
      messagingSenderId: '370553554615',
      projectId: 'playmonti-9b5c9',
      authDomain: 'playmonti-9b5c9.firebaseapp.com',
      storageBucket: 'playmonti-9b5c9.firebasestorage.app',
      measurementId: 'G-402098BYYQ',
      databaseURL:
          "https://playmonti-9b5c9-default-rtdb.europe-west1.firebasedatabase.app");

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyB5ZmfAO1nWWbYqqtrtJQ3SKT6KmMq3L1g',
      appId: '1:370553554615:android:058b58e3a5dee23e08ef32',
      messagingSenderId: '370553554615',
      projectId: 'playmonti-9b5c9',
      storageBucket: 'playmonti-9b5c9.firebasestorage.app',
      databaseURL:
          'https://playmonti-9b5c9-default-rtdb.europe-west1.firebasedatabase.app');

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyB_HRAkI4kbSRKGtWzTOOIM312qxk0nBVw',
      appId: '1:370553554615:ios:20ef5337aa6afe8d08ef32',
      messagingSenderId: '370553554615',
      projectId: 'playmonti-9b5c9',
      storageBucket: 'playmonti-9b5c9.firebasestorage.app',
      iosBundleId: 'com.example.playMonti',
      databaseURL:
          "https://playmonti-9b5c9-default-rtdb.europe-west1.firebasedatabase.app");
}
